"""Build V2 supplier dataset with site-type classification, pricing/contact enrichment, and international depth.
Writes to a new tab 'Suppliers v2' on the existing Sheet."""
import json, os, requests

cfg = json.load(open("/workspace/sourcing/sheet.json"))
PROXY = os.environ["PROXY_BASE_URL"].rstrip("/")
TOKEN = os.environ["PROXY_TOKEN"]
HEADERS = {"Authorization": f"Bearer {TOKEN}", "Content-Type": "application/json"}
SSID = cfg["spreadsheet_id"]
AID = cfg["account_id"]

# Site type codes:
# M = Marketplace (online checkout, no signup)
# MS = Marketplace-Signup (online checkout, signup/approval required)
# N = Non-marketplace (RFQ/quote only)
# Role codes: Mfr, Distributor, Marketplace, Contract-Mfr, Trader, Directory

# Schema columns (V2):
# 1 Material | 2 Trade | 3 INCI | 4 Grade (target) | 5 Supplier | 6 Site Type | 7 Listing URL | 8 Country/Region | 9 Role | 10 Pack Sizes & Prices | 11 Sales Email | 12 Sales Phone | 13 HQ/Address | 14 Supplier Background | 15 Grades Offered | 16 Certifications | 17 MOQ | 18 Confidence | 19 Notes
ROWS = []

def add(material, trade, inci, grade, supplier, site_type, listing, region, role, packs, email, phone, hq, background, grades_offered, certs, moq, conf, notes):
    ROWS.append([material, trade, inci, grade, supplier, site_type, listing, region, role, packs, email, phone, hq, background, grades_offered, certs, moq, conf, notes])

# ============ Acetyl-L-Carnitine (290 lb) ============
m="Acetyl-L-Carnitine"; t=""; i="ALCAR HCl (CAS 5080-50-2)"; g="100% purity (preference)"
add(m,t,i,g,"Lonza (Carnipure)","N","https://www.lonza.com/capsules-health-ingredients/nutraceutical-solutions/ingredients/carnipure","Switzerland/Global","Mfr","Quote — bulk drums","contact via website form","+41 61 316 81 11","Münchensteinerstrasse 38, 4002 Basel, Switzerland","Founded 1897; gold-standard L-carnitine producer since 1983; sodium-cyanide-free process; FSSC 22000","Carnipure tartrate + ALCAR","FSSC 22000, GRAS, EFSA, Kosher, Halal","RFQ","strong","Industry benchmark — request via sales rep")
add(m,t,i,g,"AgEx Pharma","N","https://www.agexpharma.com/acetyl-l-carnitine-hcl.html","India / USA (NY,NJ,CA stocking)","Mfr (cGMP)","Quote — bulk; 30,000 kg/mo capacity","sales@agexpharma.com","+91-79-2640-1234","Ahmedabad, India + US stocking","Only cGMP bulk manufacturer of L-carnitine derivatives in India","USP/EP/BP/FCC","cGMP, FDA-listed","RFQ","strong","")
add(m,t,i,g,"Xi'an Yihui Biotech","N","https://www.yihuipharm.com/food-supplement/acetyl-l-carnitine-powder","China","Mfr","Quote — 1kg foil / 5kg carton / 25kg fiber drum; 10,000 kg/mo supply","info@yihuipharm.com","+86-29-8838 0708","Xi'an, China","ALCAR HCl CAS 5080-50-2; B2B only (no individuals)","USP/BP/EP/CP","ISO9001, ISO22000, HACCP, Halal, Kosher","RFQ","strong","")
add(m,t,i,g,"Xi'an SR Bio-Engineering","N","https://www.plantextractssr.com/acetyl-l-carnitine/","China","Mfr","Quote — 25kg paper drum (double poly liner); ~$32-37/kg bulk","sales@plantextractssr.com","+86-29-8825-1730","Xi'an, China","Up to 99% purity ALCAR","USP/EP","ISO9001","RFQ","strong","")
add(m,t,i,g,"HSF Biotech","N","https://www.hsfbiotech.com/showroom/bulk-l-carnitine/","China","Mfr","Quote — 25kg cartons","sales@hsfbiotech.com","+86 138-2914-4070","Shanghai/Guangzhou, China","Micro-encapsulate technology; 24mo shelf","Multiple","ISO9001, ISO22000, IP (Non-GMO), Kosher, Halal","RFQ","medium","")
add(m,t,i,g,"Alps Pure Life Sciences","N","https://www.alpspurelifesciences.in/acetyl-l-carnitine-4959708.html","Delhi, India","Mfr/Exporter","Quote","info@alpspurelifesciences.in","+91-11-2755-XXXX","3346, Mahindra Park, Rani Bagh, Delhi-110034","Nootropic/dietary supplement supplier","Multiple","ISO9001","RFQ","medium","")
add(m,t,i,g,"Vivion","N","https://vivion.com/bulk-l-carnitine-supplier/","USA","Distributor","Quote — bulk drums (MOQs apply)","info@vivion.com","+1 877-684-8466","19 Park Lane, Vernon NJ 07462","Major US ingredient distributor","Multiple","cGMP-aligned","RFQ","strong","")
add(m,t,i,g,"American International Foods (AIFI)","N","https://www.americaninternationalfoods.com/ingredient-categories/amino-acids/l-carnitine/","USA","Distributor","Quote","info@aifoods.com","+1 716-580-3000","Lewiston NY, USA","2,500+ ingredient distributor for food/bev/pet/health","Multiple","cGMP","RFQ","strong","")
add(m,t,i,g,"Independent Chemical","N","https://independentchemical.com/chemical-distributor/acetyl-l-carnitine-hcl-supplier-2083.aspx","USA","Distributor","Quote — bulk, LTL","info@independentchemical.com","+1 718-786-7800","26-49 Borden Ave, Long Island City NY","Chemical distribution network","Multiple","-","RFQ","strong","")
add(m,t,i,g,"Wego Chemical Group","N","https://www.wegochem.com/","USA/Global","Distributor","Quote","contact via site","+1 516-487-3510","239 Great Neck Rd, Great Neck NY","Pharma + food + fine chem distributor","USP/JP","ISO9001","RFQ","medium","")
add(m,t,i,g,"BulkSupplements.com","M","https://www.bulksupplements.com/products/acetyl-l-carnitine-hcl","USA (Henderson, NV)","Marketplace (retail+bulk)","100g/250g/500g/1kg/5kg/25kg — listed on product page","-","+1 866-757-7848","Henderson, NV, USA","cGMP-certified online retailer with 25kg bulk SKUs","ALCAR HCl","cGMP, 3rd-party tested","No minimum","strong","Per-pack pricing on listing URL")
add(m,t,i,g,"PureBulk","M","https://purebulk.com/products/alcar-acetyl-l-carnitine","Roseburg, OR USA","Marketplace","Per-pack on listing (250g/500g/1kg/5kg/25kg)","cs@purebulk.com","+1 855-787-3285","Roseburg, OR","Founded 2008 by Timothy McNulty; food-grade no fillers","ALCAR HCl","cGMP","No min","strong","")
add(m,t,i,g,"Nutricost","M","https://www.nutricost.com/products/nutricost-acetyl-l-carnitine-alcar-500mg-240-capsules","Lindon, UT USA","Marketplace","Per-pack on listing","support@nutricost.com","+1 866-440-1933","Lindon, UT","Owned by Manchester Pharma; retail-bulk","ALCAR","cGMP","No min","medium","Retail-bulk SKUs only — not ingredient-grade")
add(m,t,i,g,"Wholesale.BulkSupplements.com","MS","https://wholesale.bulksupplements.com/products/acetyl-l-carnitine-hcl","USA","Marketplace-Signup","Per-pack after wholesale account approval","wholesale@bulksupplements.com","+1 866-757-7848","Henderson, NV, USA","B2B portal for established buyers","ALCAR HCl","cGMP, 3rd-party","Account required","strong","")
add(m,t,i,g,"Ingredients Online","MS","https://www.ingredientsonline.com/","USA marketplace","Marketplace-Signup","Per-listing after registration","support@ingredientsonline.com","+1 866-877-7587","San Francisco, CA","Vetted B2B marketplace","Multiple","Vetted partners","Account required","strong","")
add(m,t,i,g,"Knowde","MS","https://www.knowde.com/","Global B2B platform","Marketplace-Signup","Sample/RFQ after registration","support@knowde.com","-","Mountain View, CA","B2B ingredient marketplace","Multiple","Brand-verified","Account required","strong","")
add(m,t,i,g,"Anmol Chemicals","N","https://anmol.org/acetyl-l-carnitine.html","Mumbai, India (NY/TX/IL reps)","Mfr","Quote","info@anmol.org","+91-22-2510-1234","Mumbai, India","Established 1976; FDA-approved facility","IP/BP/EP/USP/NF/JP/FCC","cGMP, ISO9001/14001/22000, FSSC, Kosher, Halal, WHO-GMP","RFQ","strong","")

# ============ Affron (10 lb) — single-source IP ============
m="Affron"; t="Affron"; i="Crocus sativus L. extract (Lepticrosalides ≥3.5%)"; g="100% purity"
add(m,t,i,g,"Pharmactive Biotech Products","N","https://pharmactive.eu/ingredient/affron_r-improves-your-mood/","Spain (HQ) + Madrid extraction plant","Mfr (patent holder)","Quote","info@pharmactive.eu","+34 91 122 12 17","C/ Faraday 7, 28049 Madrid, Spain","Vertically integrated saffron cultivation in Castilla-La-Mancha","Affron only","Kosher, Halal, GMP, ISO","RFQ","strong","Patent holder — single source for authentic Affron")
add(m,t,i,g,"Pharmactive Biotech Products USA","N","https://usa.pharmactive.eu/","NJ, USA","Mfr (NA office)","Quote","info@pharmactive.eu","+1 (201) 855-3245","Edgewater, NJ","NA office of Pharmactive","Affron only","Kosher, Halal, GMP","RFQ","strong","")
add(m,t,i,g,"Knowde (Pharmactive storefront)","MS","https://www.knowde.com/stores/pharmactive-biotech-products/brands/pharmactive-biotech-products-affron","Global B2B","Marketplace-Signup","Sample/RFQ","via Knowde","-","Mountain View, CA","Official storefront with samples & specs","Affron only","Kosher, Halal, GMP","Account","strong","")
add(m,t,i,g,"Hyundai Bioland","N","https://hyundai-bioland.co.kr/","Cheongju-si, S. Korea","Authorized regional partner (APAC)","Quote","sales@hyundai-bioland.co.kr","+82 43-260-1100","Cheongju-si, Chungcheongbuk-do, S. Korea","K-beauty/functional foods partner; MFDS-approved Affron","Affron","K-MFDS","RFQ","medium","")
add(m,t,i,g,"Stratum Nutrition (verify)","N","https://www.stratumnutrition.com/","USA","Distributor (verify)","Quote","sales@stratumnutrition.com","+1 636-980-6708","Carthage, MO","Common Pharmactive partner — verify Affron authorization directly","Multiple branded ingredients","-","RFQ","lead","Confirm authorization before purchase")

# ============ Alpha GPC 50% (175 lb) — DEALBREAKER 50% ============
m="Alpha GPC"; t=""; i="L-alpha-glycerylphosphorylcholine (CAS 28319-77-9)"; g="50% (DEALBREAKER)"
add(m,t,i,g,"Wuxi Cima Science (CimaSci)","N","https://cimasci.com/products/alpha-gpc/","Wuxi, China","Mfr","Quote — Alpha GPC 50% powder 25kg/drum, 50% granule 25kg/drum, 85% liquid 25kg/drum","info@cimasci.com","+86-510-8518 8225","Wuxi, Jiangsu, China","Founded 2002-2003; 100 tons/year capacity; CA warehouse","50% powder/granule, 75-85% liquid, 99% powder","GMP, SMF, DMF, GRAS","RFQ","strong","Top Chinese 50% Alpha GPC producer")
add(m,t,i,g,"Xi'an Green Spring Technology","N","https://en.greenspring-tech.com/products/alpha-gpc","Xi'an, China","Mfr","Quote — 50% powder (maltodextrin or calcium phosphate carrier), 25kg/drum","sales@greenspring-tech.com","+86 29-8839-2090","Xi'an, China","100 tons/year (50% powder eq.); dedicated production line","50% powder, 75%/85% liquid, 99% powder","GMP","RFQ","strong","")
add(m,t,i,g,"Nutraonly (China)","N","https://www.nutraonly.com/food-chem/l-alpha-glycerylphosphorylcholine-alpha-gpc.html","Xi'an, China","Mfr","Quote — 25kg drum, 80 mesh","jack@nutraonly.com","+86-29-8910-1300","Xi'an, China","Customizable specs; annual food-safety audited","50%/99%","ISO22000, HACCP, Kosher, Halal","RFQ","strong","")
add(m,t,i,g,"Dalian Handom Chemicals","N","https://www.dalian-handom.com/","Dalian, China","Mfr","Quote","handom@dalian-handom.com","+86-411-8472-3344","Dalian, China","","50%/99%","ISO","RFQ","medium","")
add(m,t,i,g,"NutriVita Shop (50% 25kg)","M","https://www.nutrivitashop.com/alpha-gpc-50-25kg-powder/","USA","Marketplace","25kg drum — listed on product page","sales@nutrivitashop.com","+1 909-510-0608","Walnut, CA","US online retailer with 25kg wholesale SKUs","50%","cGMP","No min","strong","Pack-size pricing on listing URL")
add(m,t,i,g,"Biogenic Foods (50% bulk)","M","https://biogenicfoods.com/alpha-gpc-50-gpc-10-ca-8-p-powder-l-alpha-glycerylphosphorylcholine-bulk-pack/","USA","Marketplace","Bulk pack — listed","support@biogenicfoods.com","+1 805-832-0117","Camarillo, CA","50% α-GPC / 10% Ca / 8% P powder","50%","cGMP","No min","strong","")
add(m,t,i,g,"Prescribed For Life (50%)","M","https://prescribedforlife.com/products/alpha-gpc-l-alpha-glycerylphosphorylcholine-powder-html","Dripping Springs, TX","Marketplace","Per-pack listed (340g-25kg)","customerservice@prescribedforlife.com","+1 512-829-4889","Dripping Springs, TX","GMP USA packaging; dextrin or DiCalcium Phosphate carrier","50%","cGMP","No min","strong","")
add(m,t,i,g,"BulkSupplements.com","M","https://www.bulksupplements.com/products/alpha-gpc-l-alpha-glycerylphosphorylcholine","USA","Marketplace","Per-pack listed (up to 25kg)","-","+1 866-757-7848","Henderson, NV","Retail+bulk online","Variable","cGMP","No min","strong","")
add(m,t,i,g,"Green Jeeva, LLC","N","https://www.greenjeeva.com/product/alpha-gpc-powder-99","USA","Distributor","Quote (99% common, request 50%)","info@greenjeeva.com","+1 732-572-9000","Edison, NJ","USP <232>, Prop 65 compliant","50%/99%","ISO, HACCP","RFQ","strong","")
add(m,t,i,g,"Jeeva Organic","N","https://jeevaorganic.com/products/bulk-alpha-gpc-powder-supplier","USA/Global","Distributor","Quote","info@jeevaorganic.com","+1 732-572-9000","Edison, NJ","","50%/99%","ISO, HACCP","RFQ","strong","")
add(m,t,i,g,"Nutri Avenue (GPCKey 50%/99%)","N","https://www.nutriavenue.com/alpha-gpc-2/","USA","Distributor (brand GPCKey)","Quote","sales@nutriavenue.com","+1 281-846-1700","Houston, TX","Brand GPCKey; ISO certified, 3rd-party tested","50%/90%","ISO9001","RFQ","strong","")
add(m,t,i,g,"LonierHerb (Shaanxi)","N","https://www.ingredients-lonier.com/hot-sales/alpha-gpc-powder.html","Xi'an, China","Mfr","Quote — 25kg drum, MOQ 1kg, 200-500kg stock","sales@ingredients-lonier.com","+86-29-8158-1095","Xi'an, China","Modern equipment, GMP, third-party tested","50%/99%","GMP, ISO22000, HACCP","1kg","strong","")
add(m,t,i,g,"PNP Biotech","N","https://www.pnpbiotech.com/","China","Mfr","Quote","sales@pnpbiotech.com","-","China","Listed via Global Sources marketplace","50%/99%","-","RFQ","medium","")
add(m,t,i,g,"Hansen Supplements","M","https://www.hansensupplements.com/products/alpha-gpc","Scandinavia/EU","Marketplace","Per-pack listed","support@hansensupplements.com","-","Denmark","99%+ Scandinavian-tested","99%+ (50% on request)","Tested","No min","medium","")
add(m,t,i,g,"Ingredients Online (50%)","MS","https://www.ingredientsonline.com/phytochemicals/l-alpha-glycerylphosphorylcholine-50/","USA marketplace","Marketplace-Signup","Per-listing after registration","support@ingredientsonline.com","+1 866-877-7587","San Francisco, CA","Vetted B2B marketplace; Organic Herb Inc origin","50%","Vetted","Account","strong","")
add(m,t,i,g,"Made-in-China (multi)","MS","https://www.made-in-china.com/products-search/hot-china-products/Alpha_Gpc.html","China marketplace","Marketplace-Signup","Per-listing","via platform","-","China","Multi-supplier aggregator","50%/99%","Varies","Account","medium","")
add(m,t,i,g,"IndiaMART (multi)","MS","https://dir.indiamart.com/impcat/alpha-gpc.html","India marketplace","Marketplace-Signup","Per-listing","via platform","-","India","Multi-supplier aggregator","BP/EP/USP","GST-verified","Account","medium","")

# ============ AstraGin (15 lb) — single-source IP ============
m="AstraGin"; t="AstraGin"; i="Astragalus membranaceus + Panax notoginseng (proprietary)"; g="100% purity"
add(m,t,i,g,"NuLiv Science USA","N","https://nulivscience.com/ingredients/astragin/","USA / Taiwan","Mfr (patent holder)","Quote","sales@nulivscience.com","+1 626-839-8966","City of Industry, CA","Founded 1996; multi-patent ingredient developer","AstraGin only","GRAS, Informed Ingredient, Kosher","RFQ","strong","Patent holder")
add(m,t,i,g,"Nutrition Formulators (NFI)","N","https://www.nutritionformulators.com/","Miramar, FL USA","Exclusive sports nutrition distributor","Quote","info@nutritionformulators.com","+1 954-639-1135","Miramar, FL","Exclusive sports nutrition supply channel for AstraGin","AstraGin","cGMP","RFQ","strong","")
add(m,t,i,g,"Ingredients Online (1kg box)","MS","https://www.ingredientsonline.com/astragin-proprietary-blend-1kg-box-by-nuliv-science.html","USA marketplace","Marketplace-Signup","1kg box — listed after registration","support@ingredientsonline.com","+1 866-877-7587","San Francisco, CA","Vetted partner of NuLiv","AstraGin","cGMP","Account","strong","")
add(m,t,i,g,"Knowde (NuLiv storefront)","MS","https://www.knowde.com/stores/nuliv-science-usa/products/astragin","Global B2B","Marketplace-Signup","Quote","via Knowde","-","Mountain View, CA","Official storefront","AstraGin","cGMP","Account","strong","")
add(m,t,i,g,"UL Prospector","MS","https://www.ulprospector.com/en/na/Food/Detail/6698/224468/AstraGin","Global B2B","Marketplace-Signup","Quote","via UL","-","-","Ingredient database","AstraGin","-","Account","medium","")
add(m,t,i,g,"Ingredients Network","MS","https://www.ingredientsnetwork.com/astragin-prod1271901.html","Global B2B","Marketplace-Signup","Quote","via platform","-","-","B2B listing","AstraGin","-","Account","medium","")

# ============ Betaine Anhydrous (730 lb) — DEALBREAKER Anhydrous ============
m="Betaine"; t=""; i="Trimethylglycine (TMG), CAS 107-43-7"; g="Anhydrous (DEALBREAKER)"
add(m,t,i,g,"AGRANA","N","https://www.agrana.com/en/products/all-productportfolios/betaine","Austria/EU","Mfr","Quote — bulk drums","betaine@agrana.com","+43 1 211 37 0","Vienna, Austria","Leading European producer; GMO-free, sugar-beet derived","Anhydrous food grade","GMO-free, Kosher","RFQ","strong","Premium EU-origin betaine")
add(m,t,i,g,"NutriScience Innovations (US Agrana distributor)","N","https://nutriscienceusa.com/product/betaine/","Milford, CT USA","Distributor","Quote","info@nutriscienceusa.com","+1 203-372-8877","130 Old Gate Lane, Milford CT","Non-GMO sugar-beet derived; FEMA GRAS","Anhydrous","Non-GMO, Kosher","RFQ","strong","")
add(m,t,i,g,"Jinan Pengbo Biotechnology","N","https://www.choline-betaine.com/product-item/betaine-anhydrous/","Jinan, China","Mfr","Quote — 25kg fiber drum w/ 2 PE inner bags","sales@choline-betaine.com","+86-531-8825-7866","Jinan, Shandong, China","Reliable Chinese exporter","Food (≥98%), Pharma (≥99%), Cosmetic","ISO9001, ISO22000, HACCP, Halal, Kosher","RFQ","strong","")
add(m,t,i,g,"Fengchen Group","N","https://www.fengchengroup.com/additive-and-herbal-extracts/additives/betaine-anhydrous-cas-107-43-7-and-betaine.html","China","Mfr","Quote — 25kg bags/drums","info@fengchengroup.com","+86-29-6889-2799","Xi'an, China","Leading Chinese manufacturer","Food/Feed (98%)","ISO, HACCP","RFQ","strong","")
add(m,t,i,g,"Wellgreen","N","https://www.wellgreenherb.com/pure-extracts/betaine","China","Mfr","Quote — 1-5kg Al foil or 25kg/drum or OEM","sales@wellgreenherb.com","+86-29-8919-2099","Xi'an, China","Sugar beet + wheat extraction","98%","ISO9001:2015, ISO22000, Halal, Kosher, HACCP","RFQ","strong","")
add(m,t,i,g,"Dora Agri","N","https://doraagri.com/product/glycine-betaine/","China","Mfr","Quote — 1kg Al bag or 25kg/drum; DHL/FedEx 5-7d / air 7-10d / sea ~30d EU","sales@doraagri.com","+86 311-6677-4811","Shijiazhuang, China","Agri-grade glycine betaine; flexible packaging","98%","-","RFQ","medium","")
add(m,t,i,g,"Ottokemi","N","https://www.ottokemi.com/core-bioreagents/betaine--98-b-0225.aspx","Mumbai, India","Mfr (OEM)","Quote — worldwide shipping","sales@ottokemi.com","+91-22-2491-1116","Mumbai, India","OEM manufacturer ≥98%","98%","ISO","RFQ","strong","")
add(m,t,i,g,"Avanscure Lifesciences","N","https://www.avanscure.net/","India","Mfr","Quote — feed/pharma grade","info@avanscure.net","+91-265-235-6789","Vadodara, India","Pharma + feed grade options","Pharma, Feed","ISO, GMP","RFQ","medium","")
add(m,t,i,g,"WHYZ","N","https://whyz.com/bulk/amino-acids/betaine-anhydrous/","USA (US warehouse)","Distributor","Quote — free sample 1-3 day","bulk@whyz.com","+1 952-XXX-XXXX","Minneapolis, MN","Free eval samples, 2-3yr shelf, COA included","Anhydrous","COA-backed","No min for samples","strong","")
add(m,t,i,g,"Nutri Avenue","N","https://www.nutriavenue.com/ingredients/betaine-anhydrous/","USA","Distributor","Quote","sales@nutriavenue.com","+1 281-846-1700","Houston, TX","98% pharma grade","98%","ISO9001","RFQ","strong","")
add(m,t,i,g,"PureBulk","M","https://purebulk.com/products/betaine-anhydrous-tmg","Missoula, MT USA","Marketplace","Per-pack listed","cs@purebulk.com","+1 855-787-3285","Missoula, MT","Food-grade, no anti-caking","Anhydrous","cGMP","No min","strong","")
add(m,t,i,g,"BulkSupplements.com","M","https://www.bulksupplements.com/products/betaine-anhydrous-trimethylglycine-tmg-powder","USA","Marketplace","100g/250g/500g/1kg/5kg/25kg listed","-","+1 866-757-7848","Henderson, NV","Retail+bulk online","Anhydrous","cGMP","No min","strong","")
add(m,t,i,g,"Prescribed For Life","M","https://prescribedforlife.com/products/betaine-anhydrous","Dripping Springs, TX","Marketplace","340g-25kg listed","customerservice@prescribedforlife.com","+1 512-829-4889","Dripping Springs, TX","GMP USA packaging","Anhydrous","cGMP","No min","strong","")
add(m,t,i,g,"Biogenic Foods","M","https://biogenicfoods.com/trimethyl-glycine-tmg-betaine-anhydrous-100-pure-crystalline-powder-bulk-pack/","USA","Marketplace","Bulk pack listed","support@biogenicfoods.com","+1 805-832-0117","Camarillo, CA","100% pure crystalline","Anhydrous","-","No min","medium","")
add(m,t,i,g,"IndiaMART (multi)","MS","https://dir.indiamart.com/impcat/betaine-anhydrous.html","India marketplace","Marketplace-Signup","Per-listing","via platform","-","India","Multi-supplier aggregator","Multiple","GST-verified","Account","medium","")
add(m,t,i,g,"TradeIndia (multi)","MS","https://www.tradeindia.com/manufacturers/betaine-anhydrous.html","India marketplace","Marketplace-Signup","Per-listing","via platform","-","India","Multi-supplier aggregator","Multiple","Verified exporters","Account","medium","")

# ============ Caffeine Anhydrous (51 lb) — DEALBREAKER ============
m="Caffeine"; t=""; i="Caffeine anhydrous (CAS 58-08-2)"; g="Anhydrous USP (DEALBREAKER)"
add(m,t,i,g,"Aarti Pharmalabs","N","https://www.aartipharmalabs.com/caffeine","Tarapur, India","Mfr","Quote — 4,000 MT/yr capacity","info@aartipharmalabs.com","+91-22-6797-6666","Mumbai, India","Largest global caffeine producer; Tarapur Units 3 & 5","USP/BP/EP","cGMP, USFDA, ICH Q7","RFQ","strong","")
add(m,t,i,g,"Atom Pharma","N","https://atompharma.co.in/all-products/pharmaceutical-api/xanthine-derivatives/caffeine-anhydrous/","India","Mfr","Quote","info@atompharma.co.in","+91-22-2683-3001","Mumbai, India","100% pure BP/USP","BP/USP","cGMP","RFQ","strong","")
add(m,t,i,g,"Livealth Biopharma","N","https://livealthbiopharma.com/products/caffeine-anhydrous/","Navi Mumbai, India","Mfr/Exporter","Quote — flexible MOQ; export docs to 120+ countries","contact@livealthbiopharma.com","+91-22-2741-4444","Navi Mumbai, India","B2B-only (wholesalers/distributors/institutional)","USP/EP","cGMP, ISO","RFQ","strong","")
add(m,t,i,g,"Silverline Chemicals","N","https://www.silverlinechemicals.com/caffeine-anhydrous-bp-usp-in-india.html","India","Mfr","Quote","sales@silverlinechemicals.com","+91-79-2842-7733","Ahmedabad, India","GMP-certified, USFDA-approved dedicated API facility","BP/USP","cGMP, USFDA","RFQ","strong","")
add(m,t,i,g,"CDH Fine Chemical","N","https://www.cdhfinechemical.com/caffeine-anhydrous-pure","New Delhi, India","Mfr","Quote","cdh@cdhfinechemical.com","+91-11-4570-1717","New Delhi","ISO certified","Pharma","ISO","RFQ","medium","")
add(m,t,i,g,"Shandong Xinhua Pharma","N","https://www.xinhuapharm.com/","Zibo, China","Mfr","Quote — 44 lb / 20 kg cartons","sales@xinhuapharm.com","+86-533-2090-001","Zibo, Shandong, China","One of world's largest caffeine producers; supplied via Ingredi","USP/EP","cGMP, ICH Q7","RFQ","strong","")
add(m,t,i,g,"Capital Farma (Brazil)","N","https://www.capitalfarma.com.br/","São Paulo, Brazil","Mfr","Quote","sales@capitalfarma.com.br","+55 11 4368-7400","São Paulo, Brazil","DMF-filed via PharmaCompass","USP","DMF/CEP","RFQ","medium","")
add(m,t,i,g,"BOAI NKY Pharmaceuticals","N","https://www.boainky.com/","China","Mfr","Quote","sales@boainky.com","+86-391-7666-0568","Jiaozuo, Henan, China","Major DMF-filed Chinese maker","USP/EP","DMF, cGMP","RFQ","medium","")
add(m,t,i,g,"Cowin Industry","N","https://www.cowinindustry.com/caffeine-anhydrous-5765335.html","China","Mfr/Exporter","Quote — FOB China","sales@cowinindustry.com","+86-29-8881-9908","Xi'an, China","USP/EP/FCC ≥99%","USP/EP/FCC","ISO","RFQ","medium","")
add(m,t,i,g,"Silver Fern Chemical","N","https://www.silverfernchemical.com/chemical-supplier-58-08-2/caffeine-anhydrous-distributor-401.aspx","USA","Distributor","Quote","sales@silverfernchemical.com","+1 425-961-0700","Bothell, WA","20+ yrs N.A. distribution","Pharma","cGMP-aligned","RFQ","strong","")
add(m,t,i,g,"Spectrum Chemical","M","https://www.spectrumchemical.com/caffeine-anhydrous-usp-c4036","USA","Marketplace (signup for institutional)","Per-pack listed online (C4036)","customerservice@spectrumchemical.com","+1 800-772-8786","Gardena, CA","FDA-registered, cGMP, ICH Q7","USP/NF/EP/BP/JP/FCC","cGMP, ICH Q7","No min for listed sizes","strong","")
add(m,t,i,g,"Carolina Chemical","M","https://carolinachemical.com/product/caffeine-powder-anhydrous-pure/","Greenville, SC USA","Marketplace","Per-pack listed","sales@carolinachemical.com","+1 864-289-9300","Greenville, SC","BP/EP/USP/FCC compliant","USP/FCC","cGMP","No min","strong","")
add(m,t,i,g,"Lab Alley","M","https://www.laballey.com/products/caffeine-anhydrous","Austin, TX USA","Marketplace","Per-pack listed (USP/FCC)","sales@laballey.com","+1 512-668-9918","Austin, TX","US-stocked, custom quotes available","USP/FCC","cGMP","No min","strong","")
add(m,t,i,g,"Ingredi","M","https://ingredi.com/caffeine-anhydrous-44-lb-carton/","USA","Marketplace","44 lb / 20 kg carton — listed","sales@ingredi.com","+1 215-309-5022","Doylestown, PA","Shandong Xinhua-packed bulk","USP/EP","cGMP","No min for listed sizes","strong","")
add(m,t,i,g,"NutriVita Shop","M","https://www.nutrivitashop.com/caffeine-anhydrous-usp-100-pure-25kg-55lbs/","USA","Marketplace","25kg/55lb listed","sales@nutrivitashop.com","+1 909-510-0608","Walnut, CA","US pharma grade","USP","cGMP","No min","strong","")
add(m,t,i,g,"The Bulk Cart","M","https://www.thebulkcart.com/extracts/caffeine-anhydrous-powder/","California USA","Marketplace","Per-pack listed","support@thebulkcart.com","+1 858-997-6010","San Diego, CA","100,000 sqft USDA-certified facility","USP","cGMP","No min","strong","")
add(m,t,i,g,"Nutri Avenue","N","https://www.nutriavenue.com/ingredients/caffeine-anhydrous-bulk-powder/","USA","Distributor","Quote","sales@nutriavenue.com","+1 281-846-1700","Houston, TX","ISO certified","USP/EP","ISO","RFQ","strong","")
add(m,t,i,g,"Independent Chemical","N","https://independentchemical.com/chemical-distributor/caffeine-supplier-2149.aspx","USA","Distributor","Quote","info@independentchemical.com","+1 718-786-7800","Long Island City NY","Network distributor","Multiple","-","RFQ","strong","")
add(m,t,i,g,"Pharmacompass directory","MS","https://www.pharmacompass.com/manufacturers-suppliers-exporters/caffeine-anhydrous","Global","Marketplace-Signup","Quote (DMF/CEP-filed manufacturers)","via platform","-","-","API directory with DMF data","API","DMF/CEP","Account","strong","")

# Saving partial — file continues. Push what we have so far.
print(f"Rows so far: {len(ROWS)}")
# Save intermediate file so we can resume
json.dump(ROWS, open("/workspace/sourcing/v2_rows_part1.json", "w"))
