"""Update Notes tab with V2 methodology."""
import json, os, requests
cfg = json.load(open("/workspace/sourcing/sheet.json"))
PROXY = os.environ["PROXY_BASE_URL"].rstrip("/")
TOKEN = os.environ["PROXY_TOKEN"]
HEADERS = {"Authorization": f"Bearer {TOKEN}", "Content-Type": "application/json"}

notes = [
    ["Sheet structure"],
    ["• Suppliers v2 = current authoritative supplier list (19 columns, 279 rows)."],
    ["• Suppliers = v1 archive (kept for diff)."],
    ["• Materials = 26 Vita Organica ingredients with dealbreaker grade, V2 supplier counts."],
    [""],
    ["Methodology v2"],
    ["• Materials pulled from app.tenkara.ai Supabase via read-only MCP (org_id = adf29fce-7ff3-41ff-8ad9-0eba1da67a0a)."],
    ["• Grade column: pulled from materials.grade jsonb. Only DEALBREAKER grades treated as required filters."],
    ["• Volumes from DB IGNORED — sourced across all bulk quantities."],
    [""],
    ["Site Type classification (column F)"],
    ["• M = Marketplace — online checkout, no signup (e.g. BulkSupplements.com, SF Salt Co, Lab Alley, Spectrum, ChemCentral)."],
    ["• MS = Marketplace-Signup — online checkout after registration/approval (e.g. Knowde, Ingredients Online, IndiaMART, Alibaba, wholesale.bulksupplements.com)."],
    ["• N = Non-marketplace — RFQ/quote only (manufacturers like Lonza, Cargill, Pharmactive, NuLiv, NNB, Hawkins, Anmol, Aarti Pharmalabs, etc.)."],
    [""],
    ["Pricing column"],
    ["• Marketplace rows: 'Per-pack listed' or specific size/prices when visible. Visit listing URL for live pricing."],
    ["• Non-marketplace rows: 'Quote' — contact via email/phone in adjacent columns."],
    [""],
    ["Dealbreaker grades — must match these:"],
    ["• Alpha GPC: 50% (not 99%)"],
    ["• Betaine: Anhydrous"],
    ["• Caffeine: Anhydrous"],
    ["• HydroPrime: 65% Glycerol"],
    ["• Salt: Pink Himalayan (not generic sodium chloride)"],
    [""],
    ["International coverage"],
    ["• China — Shaanxi (L-citrulline, L-Tyrosine, Alpha GPC), Hebei (citrates, L-Carnitine), Hubei (taurine: Qianjiang Yongan)."],
    ["• India — Mumbai (Anmol, Aarti Pharmalabs, Atom, Livealth), Ahmedabad (AgEx, Adani), Delhi (Alpspure, CDH), Hyderabad (Botanic Healthcare), Nagpur (Herboveda)."],
    ["• Pakistan — Pink Himalayan exporters (SM Salt, PSPC, Salt Bliss, Standard Salt Works, Khewra Salt)."],
    ["• EU — AGRANA (Austria), Amino GmbH (Germany), Nektium (Spain), TAIYO GmbH (Germany)."],
    ["• Japan — Taiyo Kagaku, Ajinomoto, Sekisui Medical."],
    ["• South Africa — HG&H Pharmaceuticals (Zembrin)."],
    ["• Brazil — Capital Farma (Caffeine, DMF-filed)."],
    [""],
    ["Confidence column"],
    ["• strong = manufacturer or named authorized distributor — primary B2B contact."],
    ["• medium = reputable distributor/marketplace listing — verify authorization."],
    ["• lead = needs human follow-up."],
    [""],
    ["Single-source / IP-protected branded ingredients"],
    ["• Affron (Pharmactive), AstraGin & Senactiv (NuLiv), Capsimax (OmniActive), Infinergy (Creative Compounds), GlucoVantage & HydroPrime (NNB), ElevATP (FutureCeuticals), Nitrosigine (Everwell/Nutrition21), Zembrin (HG&H/PLT) — supply traces to one mfr + authorized distributors."],
    [""],
    ["Generated by skill: tenkara-supplier-sourcing v2"],
]
u = f"{PROXY}/{cfg['account_id']}/sheets.googleapis.com/v4/spreadsheets/{cfg['spreadsheet_id']}/values/Notes!A1:A200:clear"
requests.post(u, headers=HEADERS, json={}, timeout=30)
u = f"{PROXY}/{cfg['account_id']}/sheets.googleapis.com/v4/spreadsheets/{cfg['spreadsheet_id']}/values/Notes!A1?valueInputOption=RAW"
r = requests.put(u, headers=HEADERS, json={"values": notes}, timeout=30)
r.raise_for_status()
print("Notes tab updated.")
print("Sheet:", cfg["url"])
