"""Write Notes tab + add a Summary section."""
import json, os, requests

cfg = json.load(open("/workspace/sourcing/sheet.json"))
PROXY = os.environ["PROXY_BASE_URL"].rstrip("/")
TOKEN = os.environ["PROXY_TOKEN"]
HEADERS = {"Authorization": f"Bearer {TOKEN}", "Content-Type": "application/json"}
SSID = cfg["spreadsheet_id"]
AID = cfg["account_id"]

notes = [
    ["Note"],
    ["Organization: Vita Organica (org_id adf29fce-7ff3-41ff-8ad9-0eba1da67a0a)"],
    ["Materials queried via app.tenkara.ai Supabase (read-only MCP). 26 active materials filtered by name / trade_name / inci."],
    ["Methodology: ≥10 unique suppliers per ingredient targeted. 2.5-min cutoff per next-supplier — applied to single-source branded ingredients where authorized supply traces back to one manufacturer."],
    ["Branded/single-source ingredients (expected <10 suppliers): Affron (Pharmactive), AstraGin/Senactiv (NuLiv), Capsimax (OmniActive), Infinergy (Creative Compounds), GlucoVantage/HydroPrime (NNB Nutrition), ElevATP (FutureCeuticals), Nitrosigine (Everwell/Nutrition21), Zembrin (HG&H/PLT)."],
    ["Pricing column: 'Listed online' = the supplier's site publishes per-pack-size prices; 'Quote' = price gated behind RFQ form/email."],
    ["Confidence column: strong = primary manufacturer or named authorized distributor; medium = reputable distributor/marketplace but verify authorization; lead = needs human confirmation."],
    ["For all branded/trademarked ingredients, verify authorization status directly with the brand owner before purchase — Affron/Capsimax/Senactiv/AstraGin/Infinergy/GlucoVantage/HydroPrime/ElevATP/Nitrosigine/Zembrin are single-source IP."],
    ["This sheet was generated by the 'tenkara-supplier-sourcing' skill — reusable for any Tenkara org's material list."],
]
u = f"{PROXY}/{AID}/sheets.googleapis.com/v4/spreadsheets/{SSID}/values/Notes!A1?valueInputOption=RAW"
r = requests.put(u, headers=HEADERS, json={"values": notes}, timeout=30)
r.raise_for_status()
print("NOTES_WRITTEN")
print("Sheet URL:", cfg["url"])
